# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{kisaweb}
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jarkko Laine"]
  s.date = %q{2009-10-01}
  s.description = %q{Ruby Gem for interfacing with the SSL Kisaweb API}
  s.email = %q{jarkko@jlaine.net}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "History.md",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "kisaweb.gemspec",
     "lib/kisaweb.rb",
     "lib/kisaweb/base.rb",
     "lib/kisaweb/category.rb",
     "lib/kisaweb/club.rb",
     "lib/kisaweb/contest.rb",
     "lib/kisaweb/list_item.rb",
     "lib/kisaweb/online_ranki.rb",
     "lib/kisaweb/run.rb",
     "lib/kisaweb/runner.rb",
     "spec/category_spec.rb",
     "spec/club_spec.rb",
     "spec/contest_spec.rb",
     "spec/fixtures/clubs.txt",
     "spec/list_item_spec.rb",
     "spec/online_ranki_spec.rb",
     "spec/run_spec.rb",
     "spec/runner_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/jarkko/kisaweb}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby client for SSL Kisaweb API}
  s.test_files = [
    "spec/category_spec.rb",
     "spec/club_spec.rb",
     "spec/contest_spec.rb",
     "spec/list_item_spec.rb",
     "spec/online_ranki_spec.rb",
     "spec/run_spec.rb",
     "spec/runner_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<pauldix-typhoeus>, [">= 0.1.2"])
      s.add_runtime_dependency(%q<fastercsv>, [">= 1.5.0"])
    else
      s.add_dependency(%q<pauldix-typhoeus>, [">= 0.1.2"])
      s.add_dependency(%q<fastercsv>, [">= 1.5.0"])
    end
  else
    s.add_dependency(%q<pauldix-typhoeus>, [">= 0.1.2"])
    s.add_dependency(%q<fastercsv>, [">= 1.5.0"])
  end
end
